### PR TITLE
Fix the http location issue once for all.

### PR DESCRIPTION
**Pull request by PabloMK7**
The http header names are not case sensitive, so they kept changing and breaking the app. This fixes the issue once for all by converting both the input name and the header name to lowercase.

From: https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
```
Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive. The field value MAY be preceded by any amount of LWS, though a single SP is preferred.
```

### CODE REVIEW

**Comment by kittenchilly** [comment]
Could you upload a CIA file for this updated version here so I don't have to fiddle with compiling it myself? Doesn't look like Kunoichi is interested in updating the main repo either.

**Comment by TheGoofBall64** [comment]
yeah. if you could upload a CIA that would be great

**Comment by PabloMK7** [comment]
I will wait a few days for @KunoichiZ to confirm or deny they will do the update. Otherwise I'll have to update the repo links and build the cia myself.

**Comment by Trainax** [comment]
Hi @mariohackandglitch. Sorry to bother you. I tried following the instructions in the README file to complile the cia file myself, however I keep getting errors when lauching the `make` command.

Could you please make a tutorial on what to install from zero to compile this?

I used [devkitPro pacman](https://github.com/devkitPro/pacman) and I included [makerom](http://3dbrew.org/wiki/Makerom) and [bannertool](https://github.com/Steveice10/bannertool) in my `PATH` environment however how hard I try it doesn't find the correct libraries.

immagine

Thank you very much

**Comment by KunoichiZ** [comment]
@Trainax Don't bother, I'm working on it myself.

**Pull request merged**
