### PR TITLE
Use svcGetSystemInfo instead of svc 0x2E [doesn't work as expected]

### PR DESCRIPTION
**Pull request by hax0kartik**
Remove the deprecated 0x2E svc and replace it with svcGetSystemInfo to get luma version.

### CODE REVIEW

**Comment by KunoichiZ** [comment]
This is what I get when I tested the new changes:

[Imgur link](http://i.imgur.com/TEacXgz.jpg)

**Comment by KunoichiZ** [comment]
It turns out that user x7l7j8cc in issue #13 was right in all I had to do was change "name" to "tag_name" in source/release.cpp and it works with the previous version.cpp.

**Comment by hax0kartik** [comment]
> This is what I get when I tested the new changes

Yeah you're supposed to get that
This is unrelated to issue #13

**Comment by hax0kartik** [comment]
svc 0x2E is deprecated and will be removed in future versions of luma

**Comment by KunoichiZ** [comment]
Oh, I didn't know that. But the current installed version still shows up in red. Also, why does it say Luma3DS v8.2048-commit number next to current installed version?

**Comment by hax0kartik** [comment]
Now it will show:-
v8.2048-commit number

I can also remove the commit number if you want..

**Comment by KunoichiZ** [comment]
No, leave the commit number. I'm just confused on why it says "v8.2048" instead of "v8.0."

**Comment by hax0kartik** [comment]
I really can't tell why its returning 2048 instead of 0.Doesn't seem to be an error in my code.

**Pull request closed without merging**
