### PR TITLE
Add capability to write boot.firm to NAND as well as SD

### PR DESCRIPTION
**Pull request by hax0kartik**
Merging this commit will allow lumaupdate to write the latest boot.firm to both NAND and SD.

### CODE REVIEW

**Comment by hax0kartik** [comment]
Might need some work to make backup of older boot.firm before trying to update it.

**Comment by KunoichiZ** [comment]
Did you test this first? I just made the CIA and tested it, and I got "Reason for failure: CTR-NAND Failure" and "Couldn't open CTR-NAND for writing". Thanks for the code, though!

**Comment by hax0kartik** [comment]
Tried.Works fine for me.

**Comment by hax0kartik** [comment]
Might be some permission issue. Try adding this in the rsf under FileSystemAccesss:-
   \- Core
   \- CtrNandRo
   \- CtrNandRw
   \- CtrNandRoWrite

**Comment by KunoichiZ** [comment]
That didn't work unfortunately. I'm still getting the same error. 

EDIT: I added these to IoAccessControl (thanks to [this](https://github.com/Steveice10/buildtools/blob/1ea00aaa369d80a825002e5d514dddff2305f88b/3ds/template.rsf)):
   - FsMountNand
   - FsMountNandRoWrite
   - FsMountTwln
   - FsMountWnand
   - FsMountCardSpi

And it worked! Do you happen to know how to go about backing up and restoring the boot.firm on CTRNAND?

**Comment by hax0kartik** [comment]
Sorry for the late reply 
> Do you happen to know how to go about backing up and restoring the boot.firm on CTRNAND?

We could backup the boot.firm in CTRNAND to memory, and if download failes due to some reason we could just write the backed up boot.firm in memory to CTR-NAND.(I'm trying to do this, will submit a PR if successful)

**Comment by KunoichiZ** [comment]
Would you also know anything about making writing to CTRNAND be optional?

**Comment by hax0kartik** [comment]
>Would you also know anything about making writing to CTRNAND be optional?

Can be done but will take some time. Will pressing a combo of buttons be ok or do you want a separate option?

**Comment by KunoichiZ** [comment]
I like the button combination idea. BTW, I've disabled the CTRNAND code for the time being as people were unsure of writing directly to CTRNAND. Do you want me to enable it?

**Comment by hax0kartik** [comment]
>Do you want me to enable it?

Its better disabled until I get that backup thing to work.

**Comment by hax0kartik** [comment]
>I like the button combination idea

Excellent so which all keys should it be?

**Comment by KunoichiZ** [comment]
Should we make it be like Decrypt9 (and maybe GodMode9) with Left, Up, Right, Up, A or should we go with a smaller button combination like Left, Right, Down?

**Comment by hax0kartik** [comment]
I would personally opt for a small key combination. How about A + X?

**Comment by hax0kartik** [comment]
Just for reference don't mind.
Things done:-
- [x] Backing up payload on CTR-NAND

- [x] Check if user wants to write to CTR-NAND

- [x] Restoring backup payload.

**Comment by hax0kartik** [comment]
Alright Everything done.

**Pull request merged**
